#!/usr/bin/env bash
# run nginx running as nginx user and listen on port 8080
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed '/#user/c\user nginx' /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
